title: Rajat's Blog
email: rajatrs5054@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I'm not like them But I can pretend

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rajatsingla.in" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Rajat's Blog

date: 2017-09-04 16:26:42 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://rajatsingla.in
google_analytics: UA-82100511-1
gems: [jekyll-paginate]
cover: http://imgh.us/18491715_1350346095054522_14900553889371297_o.jpg
author_image: http://imgh.us/18447504_1350347948387670_149079611667215530_n.jpg
# Details for the RSS feed generator
author:        Rajat singla
